#!/usr/bin/perl -w
my(@gears,$final);
my(@tofirst,$i);

@gears = ();
@tofirst = ();

while ( <> ) {
	$_ =~ s/\n//;
	last if ($_ =~ /^-----/);
	push @gears,$_;
}

$final = <>;
$final =~ s/\n//;

#foreach (@gears) {
#	print $_,"\n";
#}
#print $final,"\n";

foreach (@gears) {
	push @tofirst, ( $_ / $gears[0] ) ;
}

for ($i = 0; $i <= $#gears; ++$i) {
	my($toprev);
	$toprev = 0.0;
	if ($i > 0) {
		$toprev = $gears[$i]/$gears[$i-1];
	}
	printf("%d:%6.3f%7.3f%6.3f (%.3f)\n", $i+1, $gears[$i], $gears[$i]*$final, $tofirst[$i], $toprev);
}
